---
apiVersion: v1
kind: Pod
metadata:
  name: caddy-webapp
spec:
  containers:
    - name: caddy
      image: maheshpoojaryneu/csye7125:webapp
      ports:
        - containerPort: 8080
          name: http-web-svc
      env:
        - name: CADDY_PORT
          valueFrom:
            configMapKeyRef:
              name: caddy-config
              key: CADDY_PORT
      readinessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
  imagePullSecrets:
    - name: regcred
