---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: caddy-webapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http-web-svc
      nodePort: 30000
